version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier

  poll:
    image: poll
    build:
      context: poll
      dockerfile: Dockerfile
    ports:
      - 5000:80
    networks:
      - poll-tier

  result:
    image: result
    build:
      context: result
      dockerfile: Dockerfile
    ports:
      - 5001:80
    networks:
      - result-tier
    depends_on:
      - db
        
  worker:
    image: worker
    build:
      context: worker
      dockerfile: Dockerfile
    networks:
      - back-tier
    depends_on: 
      - "redis"
      - "db"

networks:
  poll-tier:
    driver: bridge
  back-tier:
    driver: bridge
  result-tier:
    driver: bridge
volumes:
  db-data: